apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-users
data:
  port: "8001"
  db_host: mysql8:3306
  database: ms_users
  username: root
  password: "1234"
  course_url: ms-courses
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-courses
data:
  port: "8002"
  db_host: postgres14:5432
  database: ms_courses
  username: postgres
  password: "1234"
  user_url: ms-users