apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-courses
#spec : specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-courses
  template:
    metadata:
      labels:
        app: ms-courses
    spec:
      containers:
      - image: setoba06/courses:latest
        name: courses
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ms-courses
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ms-courses
                key: db_host
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: ms-courses
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ms-courses
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ms-courses
                key: password
          - name: USERS_URL
            valueFrom:
              configMapKeyRef:
                name: ms-courses
                key: user_url