apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres14
  template:
    metadata:
      labels:
        role: postgres14
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ms-courses
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ms-courses
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgresql-pvc