apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway
#spec : specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gateway
  template:
    metadata:
      labels:
        app: ms-gateway
    spec:
      containers:
      - image: setoba06/gateway:latest
        name: gateway
        ports:
        - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: ms-gateway
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: ms-gateway
  type: LoadBalancer