apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  #storageClassName: standard
  storageClassName: ""
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02df3cff56ce4d3c2
#  hostPath:
#    path: /var/lib/mysql
#    type: DirectoryOrCreate