apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  volumeName: postgres-pv
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  #storageClassName: standard
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi